[package]
name = "rust-wrapper"
version = "0.1.0"
edition = "2021"

[features]
capi = []

[dependencies]
der       = "0.7"
p256      = "0.13"
pkcs8     = { version = "0.10", features = ["std"] }
rcgen     = "0.10"
x509-cert = "0.2"

haskell-ffi = { git = "https://github.com/BeFunctional/haskell-rust-ffi.git", rev = "7685f363e2b0fa12e71aee3cebd60036a64df9f5" }

[package.metadata.capi.library]
versioning = false
